import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import "./globals.css";
import Header from "components/layout/Header/Header";
import GlobalContainer from "./components/layout/GlobalContainer/GlobalContainer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ['300', '400', '600', '700'],
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <GlobalContainer>
        {children}
        </GlobalContainer>
        
      </body>
    </html>
  );
}
